### ISSUE TITLE
min_frequency and max_frequency incremented by 0.5 after reading from config file. Any specific reason ?

### ISSUE THREAD

**Issue by gkothar1** [anujpathania/HotSniper#20]
Line:

https://github.com/anujpathania/HotSniper/blob/04d5ada1ef9ba54fc6d1ea3afc38251e4a4f9ed0/common/scheduler/scheduler_open.cc#L135

Regards,
Gaurav

**Comment by ma-rapp** [comment]
Hi Gaurav,

casting float to int truncates the values. Example: `(int)7.9 = 7`
Adding 0.5 before casting results in mathematical rounding. Example: `(int)(7.9+0.5) = (int)8.4 = 8`

see also: https://stackoverflow.com/a/9695341/4070093

Best,
Martin

**Comment by gkothar1** [comment]
I see, Thanks, Martin!

**Comment by ma-rapp** [comment]
Just for the record (in case somebody else stumbles upon this issue), this line rounds the frequencies to the next MHz (notice the multiplication by 1000).
