### ISSUE TITLE
Not able to download pinplay-drdebug : Moved permanently

### ISSUE THREAD

**Issue by imsridhar** [anujpathania/HotSniper#22]
![Screenshot from 2021-11-11 11-45-10](https://user-images.githubusercontent.com/44645257/141283417-54095eb9-9541-4019-b0b5-4aa65f5e3b19.png)

**Comment by anujpathania** [comment]
Hi Sridhar,

Unfortunately, we cannot distribute Pin directly through the repository according to the license from Intel. 

Do you know the new link where the Pin tool is moved?

**Comment by imsridhar** [comment]
in the readme pinplay section, changing 'wget' to 'curl -O' works.
`wget https://software.intel.com/content/dam/develop/external/us/en/protected/pinplay-drdebug-3.2-pin-3.2-81205-gcc-linux.tar.gz
`
`curl -O https://software.intel.com/content/dam/develop/external/us/en/protected/pinplay-drdebug-3.2-pin-3.2-81205-gcc-linux.tar.gz
`

**Comment by anujpathania** [comment]
It will be great if you can create a patch for both this issue and issues #21, when you have a stable fix ready. We will test the patch at our end independently, and then merge it into the main branch.

**Comment by anujpathania** [comment]
This updated command fixes the wget 403 forbidden error:

wget --user-agent="Mozilla"  https://www.intel.com/content/dam/develop/external/us/en/protected/pinplay-drdebug-3.2-pin-3.2-81205-gcc-linux.tar.gz
