### ISSUE TITLE
Area scaling equations

### ISSUE THREAD

**Issue by gkothar1** [anujpathania/HotSniper#25]
Hi,

HotSniper provides an equation for scaling power to nodes less than 22nm. README mentions that area has to be manually scaled to the desired node but doesn't include equations. Can you point to/include a resource that has details for scaling areas?

The closest link I found is: [http://vcl.ece.ucdavis.edu/pubs/2017.02.VLSIintegration.TechScale/VLSI-Scaling-Stillmaker.pdf](http://vcl.ece.ucdavis.edu/pubs/2017.02.VLSIintegration.TechScale/VLSI-Scaling-Stillmaker.pdf)

But not sure If the equations here apply to McPat values.

Regards,
Gaurav

**Comment by anujpathania** [comment]
Hi Gaurav,

If you mean the floor plan area, then you can multiply every floorplan's block length and width by a fixed ratio to scale the area approximately. For example, within your floorplan, if your block's Length is L and Width is W in 22nm, and you are scaling from 22nm to 14nm then your new length L' and W' at 14nm is

L' = (L/22) * 14
W' = (W/22) * 14

Of course, this is a gross simplification of the area scaling. Nevertheless, if you have accurate measures (confidence) for a floor plan on hand, then scaling in this way to a not very small or big node should not introduce too much error in your thermal simulations.

-- Anuj
