### ISSUE TITLE
Data buffer error while using Faultinjector

### ISSUE THREAD

**Issue by imsridhar** [anujpathania/HotSniper#26]
I am using the following configuration-
-n 64 -c kingscross-nuca --benchmarks=parsec-blackscholes-simmedium-14 --no-roi --sim-end=last -senergystats:100000 -speriodic-power:100000
with fastDVFS
Fault injection: type- toggle, injector- random

![Screenshot from 2022-09-16 20-54-54](https://user-images.githubusercontent.com/44645257/190674838-1c57eaed-502c-49a4-a624-c167897e6fc0.png)

**Comment by anujpathania** [comment]
Hi Sridhar,

We have no experience with fault injection framework in Sniper. To best our knowledge, this part is same as original Sniper.

If you see this error also in original Sniper, please contact them. I am afraid we are not much help here.

— Anuj
