### ISSUE TITLE
core-to-nuca address mapping

### ISSUE THREAD

**Issue by hisengberg** [anujpathania/HotSniper#27]
Dear professors:
         i am new to HotSniper, i want to know whether it distinguish between **local and remote NUCA cache accesses** for core-to-cache address mapping. 
         Can i assign the specific core to access the specific remote nuca cache or manually control the switch of the cache. Of course, it is discussed in the case of LLC.
        Hope to get your reply kindly.
Yours sincerely,
Walter

**Comment by anujpathania** [comment]
Hi Walter,

Yes, there will be a distinction between local and remote NUCA cache accesses. For example, in terms of access latency.

By default, HotSniper only supports S-NUCA wherein there is all core to all banks (static) mapping. We have several papers on S-NUCA using HotSniper.

There is no functional API for making specific cores limit there access to set of NUCA caches. Though it is "possible", and I did so in my paper "Defragmentation of Tasks in Many-Core Architecture" to implement D-NUCA. Unfortunately, modifications were unstable (lead to simulations randomly hanging) so I never publicly released the D-NUCA implementation.

-- Anuj

**Comment by hisengberg** [comment]
I see, thank you so much. I'm going to read your papers.
