### ISSUE TITLE
The URL of benchmark parsec-2.1 is no longer available

### ISSUE THREAD

**Issue by Catty2014** [anujpathania/HotSniper#49]
The URL of parsec-2.1 benchmark, parsec.cs.princeton.edu, is not available now.
The DNS resolve result of the hostname is NXDOMAIN, so I think parsec-2 might be no longer available.
Switching to parsec-3 maybe a good idea.
```
wget -O - http://parsec.cs.princeton.edu/download/2.1/parsec-2.1-core.tar.gz | tar xz --keep-old-files ; true
--2024-02-19 05:55:22--  http://parsec.cs.princeton.edu/download/2.1/parsec-2.1-core.tar.gz
Resolving parsec.cs.princeton.edu (parsec.cs.princeton.edu)... failed: Name or service not known.
wget: unable to resolve host address 'parsec.cs.princeton.edu'
```

**Comment by spolstra** [comment]
Hi,
This has been fixed. I have updated the parsec makefile, it now downloads the the parsec 2.1 tar files from another location.
