### ISSUE TITLE
Pin version issue

### ISSUE THREAD

**Issue by Vaishnavi-s112** [anujpathania/HotSniper#8]
I have tried to install pin and moved to pin_kit. But when I tried to run "make" command, I am getting the error "_Cannot find Pin in /home/vaishnavi/Desktop/project/sniper-latest/sniper/pin_kit/pin. Please download and extract Pin version 71313_" I am currently using  pin version 3.18.

**Comment by anujpathania** [comment]
Can you do a "ls" in folder "/home/vaishnavi/Desktop/project/sniper-latest/sniper/" and post the output.

Best to use the Pin version avaialbe here - "https://software.intel.com/content/dam/develop/external/us/en/protected/pinplay-drdebug-3.2-pin-3.2-81205-gcc-linux.tar.gz". Pin versions are not forward or backward compatible.

**Comment by anujpathania** [comment]
Hi. I am closing this issue because of lack of response. Please open it again if the problem persists.
