### ISSUE TITLE
mcpat.py: permission denied

### ISSUE THREAD

**Issue by imsridhar** [anujpathania/HotSniper#9]
I have followed the steps in the README file. Trying to run simulations and see results in the default setting.
On running 'run.py' file I am repeatedly getting the following output in log-

> IOError: [Errno 2] No such file or directory: '/home/sridhar/Documents/csg/hotsniper/HotSniper-master/benchmarks/energystats-temp.py'

> 558966     [  962]  [ 0]  [py_stats.cc         : 152]  *WARNING* Stats callback: return value must be (convertable into) 64-bit unsigned integer

> sh: 1: /home/sridhar/Documents/csg/hotsniper/HotSniper-master/tools/mcpat.py: Permission denied

> Traceback (most recent call last):
  File "/home/sridhar/Documents/csg/hotsniper/HotSniper-master/scripts/energystats.py", line 103, in get_stat
    self.update()
  File "/home/sridhar/Documents/csg/hotsniper/HotSniper-master/scripts/energystats.py", line 90, in update
    power = self.run_power(self.name_last, current)
  File "/home/sridhar/Documents/csg/hotsniper/HotSniper-master/scripts/energystats.py", line 160, in run_power
    execfile(outputbase + '.py', {}, result)

Finally exiting as
`
ValueError: Invalid prefix roi-end
Traceback (most recent call last):
  File "run.py", line 248, in <module>
    main()
  File "run.py", line 243, in main
    example()
  File "run.py", line 235, in example
    run(['{:.1f}GHz'.format(freq), 'maxFreq', 'slowDVFS'], get_instance(benchmark, parallelism, input_set='simsmall'))
  File "run.py", line 102, in run
    cpistack = subprocess.check_output(['python', os.path.join(SNIPER_BASE, 'tools/cpistack.py')], cwd=BENCHMARKS)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', '/home/sridhar/Documents/csg/hotsniper/HotSniper-master/tools/cpistack.py']' returned non-zero exit status 1
` 

![Screenshot from 2021-03-23 15-43-33](https://user-images.githubusercontent.com/44645257/112130741-cf389000-8bee-11eb-8778-1ee30fbc47e6.png)
![Screenshot from 2021-03-23 15-44-31](https://user-images.githubusercontent.com/44645257/112130759-d1025380-8bee-11eb-90d4-f3ad9317d74b.png)

**Comment by anujpathania** [comment]
Hi, 

There was some problems with the permissions of mcpat.py in the past. See Issue #2.

There was a fix also provided. See commit # https://github.com/anujpathania/HotSniper/commit/82e784d46d6afa933af8684651681008c17de4fa

Please confirm that you have this commit in your local repository, and if pulling it resolves your issue or not.
